### ISSUE TITLE
Fade mode reder order is incorrect.

### ISSUE THREAD

**Issue by ACIIL** [cubedparadox/Cubeds-Unity-Shaders#36]
Fade mode materials renders behind opaque materials rendering.  It looks correct in the unity editor but in-game it does not. I can only guess if it is related to the render order or if vrchat is somehow masking the fade layer with something of its own.   
 
for example, the render error will affect problems like mesh designed for emotes with transparent textures, or dress like materials with patterned holes(which is funny to see when legs render cleanly over the dress).

**Comment by netri** [comment]
To me it seems the material custom render queue is somehow ignored, I had success when I set the render queue directly in shader.

Probably somehow related to https://gamedev.stackexchange.com/questions/128811/why-does-this-transparent-shader-cause-objects-z-sorting-to-be-backwards

**Comment by netri** [comment]
To me it seems the material custom render queue is somehow ignored, I had little success when I set the render queue to transparent directly in shader.

While working on this make sure you do not fall into: https://gamedev.stackexchange.com/questions/128811/why-does-this-transparent-shader-cause-objects-z-sorting-to-be-backwards

It looks like: if material custom render queue is set to transparent
- it is still rendered as what is in the shader render queue (opaque),
- has blending enabled
- has zwrite disabled

Thus at this point it might look correct, but it depends on the distance sorting of what is rendered last. Better solution is to duplicate Flat Lit Toon name it Flat Lit Toon Transparent and change:
```
Tags
{
    "RenderType" = "Transparent"
}
```
Then use this shader in materials that are supposed to have Mode: Transparent or Fade.

Testing example:
I tested it on this avatar, it has two hair meshes.
1) the black one I want it to use fade mode, this is where I test the Flat Lit Toon Transparent shader
2) uses cutout, no issues
![image](https://user-images.githubusercontent.com/33671436/36933282-9cb10992-1ed6-11e8-8a0f-9e73ffff7a80.png)

This uses Flat Lit Toon with Mode: Fade
![image](https://user-images.githubusercontent.com/33671436/36933261-33b51460-1ed6-11e8-85e2-50a1b96b1642.png)

This uses Flat Lit Toon Transparent (created in above steps) with Mode: Fade
![image](https://user-images.githubusercontent.com/33671436/36933265-48d180b8-1ed6-11e8-8e9f-cc7b1a692ba7.png)

Flat Lit Toon Transparent has better results.
However, it appears skybox renders after Flat Lit Toon regardless of material and shader settings. Skybox from screenshots above, uses default render queue from shader. Uses default Unity's skybox shader, same happens if I use Cubedparadox's Simple Gradient Sky as skybox shader.
![image](https://user-images.githubusercontent.com/33671436/36933297-e13726c8-1ed6-11e8-9800-570bbf1808eb.png)

Unity's skybox renders after cutout and before transparent queues. So this means, **that even if we changed the shader to use transparent, it is still not rendered as transparent.**

For comparison this uses Unity's Standard shader for the hair meshes, no problems here. So conculusion is it really is an issue with the Flat Lit Toon shader and probably fixable.
![image](https://user-images.githubusercontent.com/33671436/36933430-b2d1df1a-1ed8-11e8-875f-cc2cb786572c.png)

**Comment by netri** [comment]
For some reason the render queue always stays to what is set in shader, in this case it's geometry.
Fixable if you set this inside the shader:
```
   Tags { "Queue" = "Transparent" }
```

**Comment by HelloKitty** [comment]
@netri The standard shader does not handle setting the queue in the shader with variants. Nor would creating separate versions be a good idea. It uses the Standard Shader's ShaderGUI to set queue when it detects material changes. This is handled in a method called SetupMaterialWithBlendMode.

**Comment by netri** [comment]
@HelloKitty yes that is what's odd, it works with Standard but seems to not work with Flat Lit Toon.

This might be related: https://gamedev.stackexchange.com/a/129056
When testing this I always made sure the queue was correct in inspector debug mode.
The only solution I found so far is to use another shader.

**Comment by TCL987** [comment]
I've split up the Flat Lit Toon Lite shaders into separate Opaque, Cutout, and Transparent versions to avoid this issue; if you don't care about outlines then you can use the lite version.

**Comment by cubedparadox** [comment]
TCL's changes fix this issue, closing.
